version: '3.8'

services:
  test-db:
    container_name: test-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: scheduling
      MYSQL_USER: scheduling
      MYSQL_PASSWORD: scheduling
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Different port to avoid conflict with dev database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    container_name: test-app
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      MYSQL_HOST: test-db
    depends_on:
      test-db:
        condition: service_healthy
    command: >
        bash -c "DJANGO_SETTINGS_MODULE=scheduling.test_settings python manage.py test tests"
